<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>Printer App</title>';
echo '</head>';
echo '<body>';
echo '<!-- Display the anchor text and link at the top of the page -->';
echo '<p><a href="https://printerhorizon.com/">Best Sublimation Printer</a></p>';
echo '';
echo '<h1>Printer App</h1>';
echo '';
echo '<!-- Form for user input -->';
echo '<form action="print.php" method="post">';
echo '<textarea name="content" rows="10" cols="40"></textarea><br>';
echo '<input type="submit" value="Print">';
echo '</form>';
echo '';
echo '<?php';
echo '// Process the form submission';
echo 'if ($_SERVER['REQUEST_METHOD'] === 'POST') {';
echo '$content = $_POST['content'];';
echo '';
echo '// Generate a unique file name';
echo '$filename = uniqid("print_", true) . ".txt";';
echo '';
echo '// Save the content to a text file';
echo 'if (file_put_contents($filename, $content) !== false) {';
echo '// Use the PHP exec function to print the file (Linux example)';
echo 'exec("lp " . $filename);';
echo '';
echo '// Display a success message';
echo 'echo "<p>Printing request sent successfully!</p>";';
echo '} else {';
echo '// Display an error message';
echo 'echo "<p>Error saving the file.</p>";';
echo '}';
echo '}';
echo '?>';
echo '</body>';
echo '</html>';
echo '';
?>